name: PS4 Linux Payload

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - name: make
      working-directory: linux
      run: make
    - name: make
      working-directory: linux-pro
      run: make
