name: PS4 Linux Payload

on: [ push, pull_request ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - name: make linux
      working-directory: linux
      run: make
    - name: make linux-pro
      working-directory: linux-pro
      run: make
    - name: zip
      run: zip ps4linux.zip ./*/*.bin
